name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  release:
    name: Release tfmodref
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64]
        exclude:  
          - goarch: "386"
            goos: darwin 
    steps:
    - uses: actions/checkout@v2
    - name: Bump version and push tag
      id: version
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: main
    - name: Release ${{ steps.version.outputs.new_tag }} for ${{ matrix.goos }} (${{ matrix.goarch }})
      uses: wangyoucao577/go-release-action@v1.20
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: 1.17
        binary_name: "tfmodref"
        extra_files: LICENSE README.md
        release_tag: ${{ steps.version.outputs.new_tag }}
        md5sum: true
        sha256sum: true
